# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Create environment using github token
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/environments/testenv-GH
          
      # Runs a single command using the runners shell
#      - name: Create environment using pat
#        run: |
#          curl -X PUT -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/environments/testenv-PAT
          
      # Runs a single command using the runners shell
      - name: Delete environment using github token
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/environments/testenv-GH
          
      # Runs a single command using the runners shell
#      - name: Delete environment using pat
#        run: |
#          curl -X DELETE -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/environments/testenv-PAT




